const COLOR_PRIMARY = '#17d9bd';
const COLOR_SECONDARY = '#f7f7f7';
const DEFAULT_LANGUAGE = 'en';
const SUPPORTED_LANGUAGES = ['de', 'en'];

module.exports = {
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  DEFAULT_LANGUAGE,
  SUPPORTED_LANGUAGES,
};
